import { randomBytes, scrypt as scryptCb, timingSafeEqual } from "node:crypto";
import { readFileSync } from "node:fs";
import { promisify } from "node:util";

const scrypt = promisify(scryptCb);

// Interim identity layer: local accounts with scrypt password hashes. A wallet
// sign-in (CIP-0103) can replace login() later; authorization below only relies
// on the session's party and roles.

export const APPROVAL_ROLES = ["FundReviewer", "TreasuryReviewer", "ComplianceReviewer", "AdministratorCheck", "FinalSignoff"];
export const APP_ROLES = ["Operator", "GovernanceMember", "Investor", ...APPROVAL_ROLES];
const PARTY_PATTERN = /^[A-Za-z0-9_-]{1,185}::[0-9a-f]{68}$/;
const SCRYPT = { N: 16384, r: 8, p: 1, keylen: 64 };
const SESSION_TTL_MS = 8 * 60 * 60 * 1000;
const SESSION_IDLE_MS = 30 * 60 * 1000;
const LOGIN_WINDOW_MS = 5 * 60 * 1000;
// Strict per account; looser per IP so one attacker cannot lock out everyone
// behind a shared address.
const LOGIN_MAX_PER_USER = 5;
const LOGIN_MAX_PER_IP = 30;

export async function hashPassword(password) {
  const salt = randomBytes(16);
  const hash = await scrypt(password, salt, SCRYPT.keylen, { N: SCRYPT.N, r: SCRYPT.r, p: SCRYPT.p });
  return `scrypt$${SCRYPT.N}$${SCRYPT.r}$${SCRYPT.p}$${salt.toString("base64")}$${hash.toString("base64")}`;
}

async function verifyPassword(password, encoded) {
  const [scheme, n, r, p, salt, expected] = String(encoded).split("$");
  if (scheme !== "scrypt") return false;
  const expectedBytes = Buffer.from(expected, "base64");
  const actual = await scrypt(password, Buffer.from(salt, "base64"), expectedBytes.length, { N: Number(n), r: Number(r), p: Number(p) });
  return actual.length === expectedBytes.length && timingSafeEqual(actual, expectedBytes);
}

// Used when the username is unknown so response time does not reveal it.
const DUMMY_HASH = "scrypt$16384$8$1$AAAAAAAAAAAAAAAAAAAAAA==$" + Buffer.alloc(64).toString("base64");

export function loadAccounts(path, nodeNames) {
  if (!path) return new Map();
  const parsed = JSON.parse(readFileSync(path, "utf8"));
  const users = Array.isArray(parsed?.users) ? parsed.users : [];
  const accounts = new Map();
  for (const user of users) {
    const where = `account ${JSON.stringify(user?.username)}`;
    if (typeof user?.username !== "string" || !/^[a-z0-9._-]{3,40}$/.test(user.username)) throw new Error(`${where}: invalid username`);
    if (accounts.has(user.username)) throw new Error(`${where}: duplicate username`);
    if (typeof user.passwordHash !== "string" || !/^scrypt\$\d+\$\d+\$\d+\$[A-Za-z0-9+/=]+\$[A-Za-z0-9+/=]+$/.test(user.passwordHash)) {
      throw new Error(`${where}: passwordHash must be generated by scripts/hash-password.mjs`);
    }
    if (typeof user.party !== "string" || !PARTY_PATTERN.test(user.party)) throw new Error(`${where}: invalid party`);
    if (!Array.isArray(user.roles) || user.roles.length === 0 || user.roles.some((role) => !APP_ROLES.includes(role))) throw new Error(`${where}: roles must be a non-empty subset of ${APP_ROLES.join(", ")}`);
    if (user.roles.includes("Investor") && user.roles.length > 1) throw new Error(`${where}: an Investor account cannot hold staff roles`);
    if (user.roles.includes("GovernanceMember")) {
      if (!nodeNames.includes(user.decmanNode)) throw new Error(`${where}: GovernanceMember needs a configured decmanNode`);
    } else if (user.decmanNode !== undefined && user.decmanNode !== null) {
      throw new Error(`${where}: decmanNode is only valid for GovernanceMember`);
    }
    accounts.set(user.username, Object.freeze({
      username: user.username,
      passwordHash: user.passwordHash,
      party: user.party,
      roles: Object.freeze([...user.roles]),
      decmanNode: user.decmanNode ?? null,
    }));
  }
  return accounts;
}

export function createAuth({ accounts, now = () => Date.now() }) {
  const sessions = new Map();
  const attempts = new Map();

  function throttled(key, limit) {
    const t = now();
    const entry = attempts.get(key);
    if (!entry || t - entry.started > LOGIN_WINDOW_MS) return false;
    return entry.count >= limit;
  }
  function recordFailure(key) {
    const t = now();
    const entry = attempts.get(key);
    if (!entry || t - entry.started > LOGIN_WINDOW_MS) attempts.set(key, { started: t, count: 1 });
    else entry.count += 1;
  }

  async function login(username, password, ip) {
    const userKey = `u:${String(username).slice(0, 64)}`;
    const ipKey = `ip:${ip}`;
    if (throttled(userKey, LOGIN_MAX_PER_USER) || throttled(ipKey, LOGIN_MAX_PER_IP)) return { status: "throttled" };
    const account = typeof username === "string" ? accounts.get(username) : undefined;
    const ok = await verifyPassword(typeof password === "string" ? password : "", account?.passwordHash ?? DUMMY_HASH);
    if (!account || !ok) {
      recordFailure(userKey);
      recordFailure(ipKey);
      return { status: "invalid" };
    }
    attempts.delete(userKey);
    const id = randomBytes(32).toString("base64url");
    const session = {
      id,
      csrfToken: randomBytes(32).toString("base64url"),
      username: account.username,
      party: account.party,
      roles: account.roles,
      decmanNode: account.decmanNode,
      createdAt: now(),
      lastSeen: now(),
    };
    sessions.set(id, session);
    return { status: "ok", session };
  }

  function get(id) {
    if (typeof id !== "string") return null;
    const session = sessions.get(id);
    if (!session) return null;
    const t = now();
    if (t - session.createdAt > SESSION_TTL_MS || t - session.lastSeen > SESSION_IDLE_MS) {
      sessions.delete(id);
      return null;
    }
    session.lastSeen = t;
    return session;
  }

  function logout(id) {
    sessions.delete(id);
  }

  return { login, get, logout, sessionMaxAgeSeconds: SESSION_TTL_MS / 1000 };
}

export function publicUser(session) {
  return { username: session.username, party: session.party, roles: [...session.roles] };
}

export function hasRole(session, role) {
  return Boolean(session?.roles.includes(role));
}

export function isStaff(session) {
  return Boolean(session && !session.roles.includes("Investor"));
}
